config/routes.rb
Website::Application.routes.draw do
  get "users/index"
  get "pages/about"
  get "pages/resume"
  get "pages/blog"
  get "pages/contact"
  post 'pages/contact'
  get 'log_in' => "sessions#new", :as => 'log_in'
  get 'log_out' => "sessions#destroy", :as => 'log_out'
  
  resources :posts do
    resources :comments
  end

  resources :users, only: [:index]
  resources :sessions
  root :to => 'pages#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates_presence_of :name
	validates_presence_of :message
#	validates_presence_of :email
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :foreign_key => 'post_id', dependent: :destroy
	has_attached_file :photo, :styles => {:normal => "275x180>"},
	:url  => "/assets/posts/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension"
end

app/models/user.rb
class User < ActiveRecord::Base
	# attr_accessor :password
#may want to do password confirmation
	# validates_presence_of :password
	# validates_presence_of :user_name
	# validates_uniqueness_of :user_name

	def self.authenticate(user_name,password)
		user= find_by_user_name(user_name)
		if user && user.password==password
			user
		else
			nil
		end
	end
	#if more security is needed
	#bcrypt hasing can be used
	#guide 
	#http://railscasts.com/episodes/250-authentication-from-scratch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
  		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
   helper_method :current_user

   def cur_post
   		@cur_post=Post.find params[:id]
    end
    helper_method :cur_post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    #this probalby doesn't need to exist
  end

  def new
    @post=Post.find paras[:id]
    @comment=Comment.new
    session[:return_to] || request.referer
  end

  def create
    flash[:notice] ="comment submitted!"
    @post=Post.find(comment_params[:post_id])
    @comment=@post.comments.new comment_params
   
    if @comment.save
      respond_to do |format|
          format.js {}
      end
    else render nothing => :true
    end

  end

  def edit
    @comment=Comment.find(comment_params[:id])
    session[:return_to] || request.referer
    redirect_to session[:return_to]
  end

  def update

    comment=Comment.find comment_params[:id]
    if comment.update_attributes comment_params
      redirect_to session[:return_to]
    else
          redirect_to :back, :notice => 'There was an error updating your task!'
    end
  end

  def destroy
    Comment.destroy(comment_params[:id])
  end

  def comment_params
    params.require(:comment).permit(:name,:email,:message,:post_id)
  end
  def show
    #I'm not sure if I'll ever need to show a post
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def resume
  end

  def index

  end
  def create
  	# this will have code to submit an email to bradfield.justin7@gmail.com
  	# later I want I live chat with me form but this will do
  	params.permit!
  		#code
  	respond_to do |format|
  		format.js
  		format.html
  	end
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
  def all_posts
  		@posts=Post.all.find(:all, :order => "created_at DESC")
  end
   helper_method :all_posts


	def index
		#change post.last to be a highlighted
		#post or post with highlighted set true
		@post=Post.last
		@comment=@post.comments.new

	end

	def new
		@post=Post.new
	end
	def create
		Post.create post_params
		redirect_to root_url
		respond_to do |format|
			format.js
			format.html
		end
	end
	def edit
		@post=Post.find params[:id]
		session[:return_to] || request.referer
	end

	def update
		post=Post.find post_params[:id]
		if post.update_attributes post_params
			redirect_to session[:return_to]
		else
      		redirect_to :back, :notice => 'There was an error updating your task!'
		end
	end
	def destroy
		Post.destroy(post_params[:id])
	end
	def show
		@post=Post.find params[:id]
	end
	def post_params
		params.require(:post).permit(:id,:title,:photo,:text)
	end
	private

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.authenticate(params[:user_name],params[:password])
  	if user
  		session[:user_id]=user.id
      #Change this to a user show path, which has forms
      # to create posts or manage the blog
  		redirect_to users_index_path, :notice => "logged in"
    else 
    	flash.now.alert='invalid information'
    	render 'new'
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_url, :notice => 'logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for([post,post.comments.new],remote:true) do |f|%>
<div class='span6 align-left'>
	<p>
		Name*
	</p>
	<p>
		<%=f.text_field :name, :class=>'form-control fixed-width-field'%>
	<%#=text_field_tag :email, 'email address'%>
		<%=f.hidden_field :post_id, :value=>@post.id%>
	</p>
	<p>
		Comment*
	</p>
	<p>

		<%=f.text_area :message,:rows=>'3', :class=>'form-control fixed-width-field'%>
	</p>
	<p>
	<%=submit_tag 'submit', :class => 'btn btn-primary btn-large'%>
	</p>
</div>
<%end%>

app/views/comments/_show_comment.html.erb
<% if comment.name%>
	<div class='align-left'>
		<h4><%=comment.name%></h4>
		<p class='well comment'><small><%=comment.message%></small>
		</p>
	</div>
<%end%>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/showmore.js.erb
// This file will be used to append 
//more comments when somebody hits a 
//show more button

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jusitn Bradfield</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  
  <%= javascript_include_tag 'jquery', 'autoresize.jquery',"application", 'data-turbolinks-track'=>true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to 'JustinB', root_url,:class =>'brand darken-on-hover' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "About",pages_about_path %></li>
            <li><%= link_to "Resume",pages_resume_path %></li>
            <li><%= link_to "Blog",posts_path%> </li>
            <li><%= link_to "Contact",pages_contact_path %> </li>
            <%=render '/shared/login_button' %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row-fluid">
      <div class="span2 lightly-colored">
        <%= yield :sidebar %>
      </div>
      <div class="span10">
        <%= yield :main %>
      </div>
    </div>
    <div class='row-fluid lightly-colored' id='footer'>
       <%= render '/shared/footer'%>
    </div>
  </div>
</body>
</html>

app/views/layouts/application_original.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/pages/_message_form.html.erb
<%= form_for :message, :remote=>true,  :html => { :id => 'message_form' } do |f|%>
<div class='span6 align-left'>
	<p>
		Name*
	</p>
	<p>
		<%=f.text_field :name, :class=>'form-control fixed-width-field'%>
	</p>
	<p>
		Email Address*
	</p>
	<p>
		<%=f.text_field :address, :class=>'form-control fixed-width-field'%>
	</p>
	<p>
		Comment*
	</p>
	<p>

		<%=f.text_area :message,:rows=>'3', :class=>'form-control fixed-width-field'%>
	</p>
	<p>
	<%=submit_tag 'submit', :class => 'btn btn-primary btn-large' , :id=> 'submit_message'%>
	</p>
</div>
<%end%>

app/views/pages/about.html.erb
<% content_for :sidebar do%>
<h3>another picture!</h3>
<p>
	This section describes some of the basics
	about me that are not on my resume.  If you want to learn more about me visit my linkedin, facebook, or github webpages,read my blog, or contact me through email/text.  
</p>

<% end %>

<% content_for :main do%>
<div class='hero-unit'>
	<h1>About</h1>
	<p class='well'>Hello there, </br>
	my name is Justin Bradfield.  I'm originaly from Iowa and currently living in Boston.  Right now I spend most of days programing or looking for jobs at start ups. I really enjoy finding and learning languages that make a certain tast easier.  Rails development, while it's hard to get used to, is exaclty that. I've also been getting into processing recently. It's a great way sidestep tricky syntax and make apps that are fun or informative.  Besides programing I consider myself a pretty decent tennis and table tennis player as well as a huge Green bay Packers and Chicago Cubs fan(you win some you lose some). If you want to know more about me visit my <%=link_to 'linkedin','http://www.linkedin.com/in/justinbradfield' %> account or contact me.</p>
<%end%>

app/views/pages/blog.html.erb
<% content_for :sidebar do%>

	<p> A picture of me should go here.  Not extremely professional though</p>
	
	<h3> Hello </h3>

	<p>
		My name is Justin.  This is my new website.  On the right you will find a highlighted post, most likely about tehnology, coding, music, or food.  Feel free to explore the website. Thanks for visiting.  
	</p>

<%end%>

<% content_for :main do%>
	<%=render '/posts/post_box', :post => @posts.first %>
<%end%>

app/views/pages/contact.html.erb
<%content_for :sidebar do%>
	<h3> Visit</h3>
	 my profiles on any of the following links, or send me a message </br>
	<!-- REPLACE LINKS WITH IMAGES-->	
	<ul id='nav-list'>
		<li>
			<%=link_to 'linkedin','http://www.linkedin.com/in/justinbradfield' %>
		</li>
		<li>
			<%=link_to 'github','http://www.linkedin.com/in/justinbradfield' %>
		</li>
		<li>
			<%=link_to 'facebook','http://www.facebook.com/justin.bradfield2' %>
		</li>
	</ul>
<%end%>

<%content_for :main do%>
<div class='hero-unit'>
	<h2>Send me a message</h2>
	<%=render 'message_form' %>
</div>



<%end%>

app/views/pages/index.html.erb
<% content_for :sidebar do%>

	<p> A picture of me should go here.  Not extremely professional though</p>
	
	<h3> Hello </h3>

	<p>
		My name is Justin.  This is my new website.  On the right you will find a highlighted post, most likely about tehnology, coding, music, or food.  Feel free to explore the website. Thanks for visiting.  
	</p>

<%end%>

<% content_for :main do%>
<div class='hero-unit'>
	<h2> Welcome <small classs='muted'> have some fun this processing sketch while you're here</small></h2>
	<%=render '/shared/processing'%>
</div>
<%end%>

app/views/pages/resume.html.erb
<% content_for :sidebar do%>

<%end%>

<% content_for :main do%>
	<h1>Pages#resume</h1>
	<p>Find me in app/views/pages/resume.html.erb</p>
<%end%>

app/views/posts/_comment_list.html.erb
<div class='comments align-left create-space'>
	<h3>Comments</h3>

	<% if @post.comments%>
		<% @post.comments.each do |comment|%>
			<%=render '/comments/show_comment', :comment => comment%>
			
		<%end%>
	<%else%>
			Be the first to comment
	<%end%>
</div>
<div class='span 8 centered'>
	<%=render '/comments/comment_form', :post => @post%>
</div>
		

app/views/posts/_post_box.html.erb
<% if @post %>
	<p></p>

	<h1 class='smaller-h1  create-space'> <%= @post.title%></h1>
	<%= image_tag @post.photo(:normal), :class => "img-rounded create-space" %>
	<p class='pagination-centered'>
		<%= @post.text %>
	</p>
	<%= render 'comment_list',:post => @post%>
<%end%>

app/views/posts/_post_list.html.erb
<h3> Posts </h3>
<ul id='nav-list'>
	<%all_posts.each do |post|%>
		<li>
			<%= link_to post.title,post%>
		</li>
	<%end%>
</ul>

app/views/posts/index.html.erb
<% content_for :sidebar do%>
	<%= render 'post_list'%>
<%end%>


<% content_for :main do%>
<div class='hero-unit pagination-centered'>
		<h2 class='align-left'> Highlighted </h2>
		<%=render 'post_box' %>
</div>
<%end%>

app/views/posts/new.html.erb
<%=form_for @post, :html => {:multipart => true} do |f|%>
<%= f.label :title%><br/>
<%= f.text_field :title %><br/>
<%= f.label 'description', :text%><br/>
<%= f.text_area :text %><br/>
<%= f.label :photo %>
<%= f.file_field :photo%>
<%=submit_tag 'Submit'%>
<%end%>

app/views/posts/show.html.erb
<% content_for :sidebar do%>
	<%=render 'post_list'%>
<%end%>


<% content_for :main do%>
<div class='hero-unit pagination-centered'>
	<small> <%=@post.created_at.strftime('%F')%> </small>
	<%=render 'post_box'%>
</div>
<%end%>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class='span12'>
	<p> this is the footer it will have links, and mabye a log in or subscribe form when it's finished </p>
</div>

app/views/shared/_login_button.html.erb
<% if current_user %>
	<li><%= link_to "logout",session_path(current_user), :method => 'delete' %> </li>
<%else%>
	<li><%= link_to "Admin",new_session_path %> </li>
<%end%>

app/views/shared/_processing.html.erb
<script type="text/processing" data-processing-target="mycanvas">
<%=render '/processing/attraction.js'%>
</script>
<canvas id="mycanvas"></canvas>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>